# Generated by Django 5.0.3 on 2024-04-17 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idProduct', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=32)),
                ('product', models.CharField(max_length=32)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(max_length=512)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('idSelling', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=32)),
                ('date', models.DateTimeField(default=17)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('idPerson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
        ),
    ]
