# Generated by Django 5.0.3 on 2024-04-17 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('idRace', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('race', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('idPet', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('birth', models.DateField()),
                ('pure', models.BooleanField(default=True)),
                ('gender', models.BooleanField()),
                ('castrated', models.BooleanField()),
                ('socLevel', models.CharField(choices=[('Low', 'B'), ('Medium', 'M'), ('High', 'A')], default='High', max_length=6)),
                ('obs', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('idPerson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('idRace', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pet.race')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='dayCare',
            fields=[
                ('idDayCare', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('quotas', models.PositiveSmallIntegerField()),
                ('idPerson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('idPet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pet.pet')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('idRide', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('quotas', models.PositiveSmallIntegerField()),
                ('idPerson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('idPet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pet.pet')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddConstraint(
            model_name='daycare',
            constraint=models.UniqueConstraint(fields=('idDayCare', 'idPerson', 'idPet', 'date'), name='const_dayCare_distinct'),
        ),
        migrations.AlterUniqueTogether(
            name='daycare',
            unique_together={('idDayCare', 'idPerson', 'idPet', 'date')},
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.UniqueConstraint(fields=('idPerson', 'name'), name='const_pet_distinct'),
        ),
        migrations.AlterUniqueTogether(
            name='pet',
            unique_together={('idPerson', 'name')},
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.UniqueConstraint(fields=('idRide', 'idPerson', 'idPet', 'date'), name='const_ride_distinct'),
        ),
        migrations.AlterUniqueTogether(
            name='ride',
            unique_together={('idRide', 'idPerson', 'idPet', 'date')},
        ),
    ]
