# Generated by Django 4.0.4 on 2022-06-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('idLocalidad', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('localidad', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUser', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('fecha_nac', models.DateField()),
                ('cel', models.BigIntegerField()),
                ('dir', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('habilitado', models.BooleanField(default=False)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Usuario.localidad')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mascota.mascota')),
            ],
        ),
    ]
