# Generated by Django 4.0.4 on 2022-06-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mascota', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guarderia', models.DateField()),
                ('precio', models.PositiveIntegerField()),
                ('fecha', models.DateField(auto_now=True)),
                ('cupos', models.PositiveSmallIntegerField(default=6)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mascota.mascota')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Usuario.usuario')),
            ],
        ),
    ]
