# Generated by Django 4.0.4 on 2022-06-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('idRaza', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('raza', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('puro', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=128)),
                ('sexo', models.BooleanField()),
                ('fecha_nac', models.DateField()),
                ('castrado', models.BooleanField()),
                ('nivel_soc', models.PositiveSmallIntegerField(default=0)),
                ('obs', models.CharField(max_length=128)),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mascota.raza', unique=True)),
            ],
        ),
    ]
